### ISSUE TITLE
optional dependencies

### ISSUE THREAD

**Issue by seanbreckenridge** [karlicoss/kompress#4]
btw not sure if this installs `zstandard` or not? Assumes its [this lib](https://pypi.org/project/zstandard/), but right now don't see anything in the pyproject file to install that

same with lz4?

rest of the stuff looks to be python stdlib

unless im misunderstanding, should probably catch an importerror and warn if the third party libs are not installed

can PR if you think thats good

**Comment by karlicoss** [comment]
yeah it's zstandard on pip! And yep -- I didn't add the optional dependency yet (apparently there are no tests for it 🙈).
I think we should keep imports for the third party archivers on the use site so we don't have to write defensive code -- it seems fair to just crash if the compressor isn't installed when you try to uncompress the file (not much else we can do otherwise).
Could add a suggestion to install it though, e.g. pip install kompress[zstd] or something like that for the ease of use

**Comment by seanbreckenridge** [comment]
will pr some docs for that (at least mention them in the readme)

**Comment by karlicoss** [comment]
added zstd dependency here btw, needed it for my setup anyway! https://github.com/karlicoss/kompress/pull/5
